name: transactions_lake
version: '1.0.0'
config-version: 2

profile: transactions_lake

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - target
  - dbt_packages
